name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - develop  # Se ejecuta CI cuando se hace push en la rama develop
      - main     # Se realiza el deploy cuando se hace push en la rama main

jobs:
  build:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Versión de Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test