name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - develop  # Se ejecuta CI cuando se hace push en la rama develop
      - main     # Se realiza el deploy cuando se hace push en la rama main

jobs:
  build:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test