name: CI Pipeline for React App

on:
  pull_request:
    branches:
      - develop  # Se ejecuta CI cuando hay un PR hacia la rama develop
  push:
    branches:
      - main  # Se realiza el deploy cuando se hace merge en la rama main

jobs:
  build:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - run: npm install
        - run: npm run build --if-present
        - run: npm test

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_FILE }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Create temp directory
        run: |
          echo "{{ vars.EC2_PUBLIC_IP }}"
          ssh -i ec2-key.pem ec2-user@{{ vars.EC2_PUBLIC_IP }} 'sudo mkdir /home/ec2-user/temp_build/'

      - name: Copy Files to EC2 Temporary Directory
        run: |
          scp -i ec2-key.pem -r ./build/* ec2-user@{{ vars.EC2_PUBLIC_IP }}:/home/ec2-user/temp_build/

      - name: Move Files to NGINX Directory
        run: |
          ssh -i ec2-key.pem ec2-user@{{ vars.EC2_PUBLIC_IP }} 'sudo mv /home/ec2-user/temp_build/* /usr/share/nginx/html/'

      - name: Restart NGINX
        run: |
          ssh -i ec2-key.pem ec2-user@{{ vars.EC2_PUBLIC_IP }} 'sudo systemctl restart nginx'